Repository MetaMask/snaps, pull requests merged in 2024-05, with the labels that each got.

#2418 chore(devdeps): @lavamoat/allow-scripts@^3.0.3>^3.0.4
  package.json
  packages/create-snap/package.json
  packages/examples/package.json
  packages/examples/packages/bip32/package.json
  packages/examples/packages/bip44/package.json
  packages/examples/packages/browserify-plugin/package.json
  packages/examples/packages/browserify/package.json
  packages/examples/packages/client-status/package.json
  packages/examples/packages/cronjobs/package.json
  packages/examples/packages/dialogs/package.json
  packages/examples/packages/errors/package.json
  packages/examples/packages/ethereum-provider/package.json
  packages/examples/packages/ethers-js/package.json
  packages/examples/packages/get-entropy/package.json
  packages/examples/packages/get-file/package.json
  packages/examples/packages/home-page/package.json
  packages/examples/packages/images/package.json
  packages/examples/packages/interactive-ui/package.json
  packages/examples/packages/invoke-snap/package.json
  packages/examples/packages/invoke-snap/packages/consumer-signer/package.json
  packages/examples/packages/invoke-snap/packages/core-signer/package.json
  packages/examples/packages/json-rpc/package.json
  packages/examples/packages/jsx/package.json
  packages/examples/packages/lifecycle-hooks/package.json
  packages/examples/packages/localization/package.json
  packages/examples/packages/manage-state/package.json
  packages/examples/packages/name-lookup/package.json
  packages/examples/packages/network-access/package.json
  packages/examples/packages/notifications/package.json
  packages/examples/packages/rollup-plugin/package.json
  packages/examples/packages/signature-insights/package.json
  packages/examples/packages/transaction-insights/package.json
  packages/examples/packages/wasm/package.json
  packages/examples/packages/webpack-plugin/package.json
  packages/snaps-browserify-plugin/package.json
  packages/snaps-cli/package.json
  packages/snaps-controllers/package.json
  packages/snaps-execution-environments/package.json
  packages/snaps-jest/package.json
  packages/snaps-rollup-plugin/package.json
  packages/snaps-rpc-methods/package.json
  packages/snaps-sdk/package.json
  packages/snaps-utils/package.json
  packages/snaps-webpack-plugin/package.json
  yarn.lock
Labels: type-security, dependencies

#2428 Add support for `ed25519Bip32` to the BIP-32 example snap
  packages/examples/packages/bip32/snap.manifest.json
  packages/examples/packages/bip32/src/index.test.ts
  packages/examples/packages/bip32/src/index.ts
  packages/examples/packages/bip32/src/types.ts
  packages/test-snaps/src/features/snaps/bip32/BIP32.tsx
  packages/test-snaps/src/features/snaps/bip32/components/SignMessage.tsx
Labels: team-snaps-platform

#2442 deps: @metamask/providers 17
  packages/snaps-execution-environments/package.json
  packages/snaps-sdk/package.json
  packages/test-snaps/package.json
  yarn.lock
Labels: dependencies
